name: table_calendar
description: Flutter Calendar organized neatly into a Table. Features events and different calendar formats. Autosizes vertically, saving space for other widgets.
version: 0.1.4
author: Aleksander Wo≈∫niak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.15.7
  date_utils: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: