name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.9
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/table_calendar/assets/images/icons8-go-back-64.png
    - packages/table_calendar/assets/images/icons8-circled-right-64.png
